name: Build EngineApp
on:
  push:
    branches: [main]

env:
  PREMAKE_VERSION: 5.0.0-beta2

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v3
        with:
          repository: "MeerkatEngine/mingw-w64-MeerkatEngine"
      - name: Bootstrap and build EngineApp
        shell: powershell
        run: |
          New-Item -Path .\build -ItemType Directory -Force
          Set-Location -Path .\build
          ..\bootstrap.ps1
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: EngineApp-windows
          path: build/bin
  
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential libsdl2-dev imagemagick automake autoconf wget
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/checkout@v3

      - name: Install premake5
        run: |
          mkdir -p build
          cd build
          wget https://github.com/premake/premake-core/releases/download/v${PREMAKE_VERSION}/premake-${PREMAKE_VERSION}-src.zip
          unzip premake-${PREMAKE_VERSION}-src.zip >/dev/null
          cd premake-${PREMAKE_VERSION}-src
          make -f Bootstrap.mak linux
          sudo cp bin/release/premake5 /usr/local/bin

      - name: Checkout SDL2_image
        uses: actions/checkout@v3
        with:
          repository: 'libsdl-org/SDL_image'
          ref: 'SDL2'
          path: 'build/SDL2_image'
      - name: Build SDL2_image
        run: |
          cd build/SDL2_image
          git apply ../../.github/patches/SDL2_image.patch
          mkdir -p build
          cd build
          ../configure
          make
          sudo make install

      - name: Generate Makefiles
        run: premake5 gmake
      - name: Build project (Debug)
        run: make -C build config=debug
      - name: Upload build (Debug)
        uses: actions/upload-artifact@v3
        with:
          name: EngineApp-linux-debug
          path: build/bin/Debug
      - name: Build project (Release)
        run: make -C build config=release
      - name: Upload build (Release)
        uses: actions/upload-artifact@v3
        with:
          name: EngineApp-linux-release
          path: build/bin/Release
